### ISSUE TITLE
主题Webp随机优化图片bug

### ISSUE THREAD

**Issue by okatu-loli** [mirai-mamori/Sakurairo#238]
**问题出处：**

这个问题出在程序的哪一个具体功能？
       Webp随机优化图片
**实际行为描述：**
      按照文档填入相关参数，数据库数据也显示正常，但打开https://lengfan.me/wp-json/sakura/v1/image/cover （主题内置的 
       随机图片api）报错
触发问题后造成了什么效果及影响？
       无法正常显示随机图
**预期的行为：**

这个功能应该有怎样的效果和影响？
       主页背景等随机图片

**复现步骤：**

怎样才能再次触发这个问题？
按照主题文档设置随机图，用的阿里云oss
**配置与环境：**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：8
- 数据库类型 / 版本：mysql5.7
- WordPress 版本：5.7.2
- 主题版本：（Release 标注的版本号）2.1.1.1
- 使用的插件：（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：（浏览器名称及版本号）

**报错信息**
```
Fatal error: Uncaught TypeError: array_rand(): Argument #1 ($array) must be of type array, null given in /www/wwwroot/lengfan.me/wp-content/themes/Sakurairo/inc/classes/Images.php:155 
Stack trace: #0 /www/wwwroot/lengfan.me/wp-content/themes/Sakurairo/inc/classes/Images.php(155): array_rand() 
#1 /www/wwwroot/lengfan.me/wp-content/themes/Sakurairo/inc/api.php(119): Sakura\API\Images::cover_gallery() 
#2 /www/wwwroot/lengfan.me/wp-includes/rest-api/class-wp-rest-server.php(1139): cover_gallery() 
#3 /www/wwwroot/lengfan.me/wp-includes/rest-api/class-wp-rest-server.php(985): WP_REST_Server->respond_to_request() 
#4 /www/wwwroot/lengfan.me/wp-includes/rest-api/class-wp-rest-server.php(412): WP_REST_Server->dispatch() 
#5 /www/wwwroot/lengfan.me/wp-includes/rest-api.php(354): WP_REST_Server->serve_request() 
#6 /www/wwwroot/lengfan.me/wp-includes/class-wp-hook.php(292): rest_api_loaded() 
#7 /www/wwwroot/lengfan.me/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() 
#8 /www/wwwroot/lengfan.me/wp-includes/plugin.php(551): WP_Hook->do_action() 
#9 /www/wwwroot/lengfan.me/wp-includes/class-wp.php(388): do_action_ref_array() 
#10 /www/wwwroot/lengfan.me/wp-includes/class-wp.php(750): WP->parse_request() 
#11 /www/wwwroot/lengfan.me/wp-includes/functions.php(1291): WP->main() 
#12 /www/wwwroot/lengfan.me/wp-blog-header.php(16): wp() 
#13 /www/wwwroot/lengfan.me/index.php(17): require('...') 
#14 {main} thrown in /www/wwwroot/lengfan.me/wp-content/themes/Sakurairo/inc/classes/Images.php on line 155
此站点遇到了致命错误。

了解有关对WordPress进行故障排除的更多信息。
```
**补充信息：**

提供尽可能多的相关信息。

**Comment by KotoriK** [comment]
请确认manifest.json已经写入在数据库中
设置中有将manifest.json更新至数据库的入口
```
如果你选择使用Webp优化随机图片，请点击 这里 来更新 Manifest 路径
```

**Comment by bymoye** [comment]
无法复现
